LIB =	tinyxml

SRCS =				\
	tinystr			\
	tinyxml			\
	tinyxmlerror		\
	tinyxmlparser		

ifndef OURO_ROOT
export OURO_ROOT := $(subst /ouro/src/lib/dependencies/$(LIB),,$(CURDIR))
endif

include $(OURO_ROOT)/ouro/src/build/common.mak