# -*- coding: utf-8 -*-

"""
Django settings for OUROWebConsole project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import django

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(z-^8#+9$zm1fz^k7c-g!$%8d62d3jaomcl4f05%4kxqj71o2_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'WebConsole',
)

if django.VERSION < (1, 7):
	MIDDLEWARE_CLASSES = (
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    #'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	)

if django.VERSION >= (1, 8):
	MIDDLEWARE_CLASSES = (
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    #'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	    'django.middleware.security.SecurityMiddleware',
	)

ROOT_URLCONF = 'OUROSettings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # The template file storage path, you can have multiple
        'DIRS': [
            BASE_DIR + "/templates"
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OUROSettings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Static file storage path, you can have multiple
STATICFILES_DIRS  = (
    os.path.join(BASE_DIR, "static"),
)

if django.VERSION < (1, 7):
	# for Django-1.6.11
	TEMPLATE_DIRS = ( BASE_DIR + "/templates", )
	TEMPLATE_DEBUG = True
	TEMPLATE_CONTEXT_PROCESSORS = (
	    'django.core.context_processors.request',
	)

# BOOL
# Whether to use the Machines of the buffer mechanism;
# The use of these mechanisms can be slowed down when the page opens Caton phenomenon,
# But for real, there will be some deviation
# Note: this mechanism only in a separate runtime is set to true,
#       If you are deploying to apache and other http servers on the later this argument is still True,
#       It is possible to cause a large number of udp broadcast packets
USE_MACHINES_BUFFER = True

# FLOAT；单位：秒
# When and for how long no query Machines related data is stopped when the buffer mechanism,
# To avoid a long time without people operation also kept the broadcast query packet
STOP_BUFFER_TIME = 300

# FLOAT; unit: seconds
# Machines buffer mechanism of the refresh interval
# Interval time the shorter, the more precise, the transmission of data more frequently
# This parameter is only in the USE_MACHINES_BUFFER = True When acting
MACHINES_BUFFER_FLUSH_TIME = 1.0

# FLOAT；Unit: seconds
# Each time you query the Machine when waiting for a response for the longest time
MACHINES_QUERY_WAIT_TIME = 1.0

# MACHINES address configuration
# When this parameter is not empty, then from the original broadcast probe to a fixed address detection,
# WebConsole only in this configuration of the address detection,
# When the presence Server across the network case, this scenario is still useful.
# Example:
# MACHINES_ADDRESS = ["192.168.0.1", "10.0.0.1", "172.16.0.1"]
MACHINES_ADDRESS = []
