LIB =	g3dlite

SRCS =				\
	AABox			\
	Box			\
	Crypto			\
	format			\
	Matrix3			\
	Plane			\
	System			\
	Triangle		\
	Vector3			\
	Vector4

ifndef OURO_ROOT
export OURO_ROOT := $(subst /ouro/src/lib/dependencies/$(LIB),,$(CURDIR))
endif

include $(OURO_ROOT)/ouro/src/build/common.mak