LIB =	jwsmtp

SRCS =				\
	base64			\
	compat			\
	mailer

ifndef OURO_ROOT
export OURO_ROOT := $(subst /ouro/src/lib/dependencies/jwsmtp/jwsmtp/$(LIB),,$(CURDIR))
endif

include $(OURO_ROOT)/ouro/src/build/common.mak