LIB =	tmxparser

SRCS =				\
	base64			\
	TmxEllipse		\
	TmxImage		\
	TmxImageLayer		\
	TmxLayer		\
	TmxMap			\
	TmxObject		\
	TmxObjectGroup		\
	TmxPolygon		\
	TmxPolyline		\
	TmxPropertySet		\
	TmxTile			\
	TmxTileset		\
	TmxUtil			


ifndef OURO_ROOT
export OURO_ROOT := $(subst /ouro/src/lib/dependencies/$(LIB),,$(CURDIR))
endif

include $(OURO_ROOT)/ouro/src/build/common.mak