# -*- coding: utf-8 -*-

"""
Django settings for OUROWebConsole project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import django

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(z-^8#+9$zm1fz^k7c-g!$%8d62d3jaomcl4f05%4kxqj71o2_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	'WebConsole',
)

if django.VERSION < (1, 7):
	MIDDLEWARE_CLASSES = (
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		#'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
	)

if django.VERSION >= (1, 8):
	MIDDLEWARE_CLASSES = (
		'django.contrib.sessions.middleware.SessionMiddleware',
		'django.middleware.common.CommonMiddleware',
		#'django.middleware.csrf.CsrfViewMiddleware',
		'django.contrib.auth.middleware.AuthenticationMiddleware',
		'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
		'django.contrib.messages.middleware.MessageMiddleware',
		'django.middleware.clickjacking.XFrameOptionsMiddleware',
		'django.middleware.security.SecurityMiddleware',
	)

ROOT_URLCONF = 'OUROSettings.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		# Template file storage path, there can be multiple
		'DIRS': [
			BASE_DIR + "/templates"
			],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'OUROSettings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
	}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

#LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Static file storage path, there can be multiple
STATICFILES_DIRS  = (
    os.path.join(BASE_DIR, "static"),
)

if django.VERSION < (1, 7):
	# for Django-1.6.11
	TEMPLATE_DIRS = ( BASE_DIR + "/templates", )
	TEMPLATE_DEBUG = True
	TEMPLATE_CONTEXT_PROCESSORS = (
		'django.core.context_processors.request',
	)

# BOOL
# Whether to use the buffering mechanism of Machines;
# Use some mechanism to slow down the jam when the page is opened.
# But for real-time, there will be some deviation
# Note: This mechanism can only be set to true when running independently.
# If you deploy to an http server such as apache, this parameter is still True.
# There may be a large number of udp broadcast packets
USE_MACHINES_BUFFER = True

# FLOAT;Unit: second
# How long does it stop the buffering mechanism when there is no query for Machines related data?
# Avoid broadcasting broadcast query packages that are not in operation for a long time
STOP_BUFFER_TIME = 300

# FLOAT;Unit: second
# Machines buffer mechanism refresh interval
# The shorter the interval, the more accurate, the more frequently the data is sent.
# This parameter only works when USE_MACHINES_BUFFER = True
MACHINES_BUFFER_FLUSH_TIME = 1.0

# FLOAT;Unit: second
# The longest time to wait for a response every time you query Machine
MACHINES_QUERY_WAIT_TIME = 1.0

# MACHINESAddress Configuration
# When this parameter is not empty, the original broadcast probe is changed to fixed address probe.
# WebConsole will only detect with this configured address.
# This scheme is useful when the server has cross-network segments.
# Example:
# MACHINES_ADDRESS = ["192.168.0.1", "10.0.0.1", "172.16.0.1"]
MACHINES_ADDRESS = []

